// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATmqXIUBc1ERuQLXESrrcq1QKJrhTHJxM',
    appId: '1:926705414960:web:063889540af7feb019cef5',
    messagingSenderId: '926705414960',
    projectId: 'ingredientbutler',
    authDomain: 'ingredientbutler.firebaseapp.com',
    storageBucket: 'ingredientbutler.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl-nSzpPuZkK-2AKlyfIjAyBstaTdObHA',
    appId: '1:926705414960:android:a9ef88fb3cca3bdc19cef5',
    messagingSenderId: '926705414960',
    projectId: 'ingredientbutler',
    storageBucket: 'ingredientbutler.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM6wkHfZQDk0tnymlswHB1NjbZDzfwrto',
    appId: '1:926705414960:ios:7224ea9b2f5f0f3c19cef5',
    messagingSenderId: '926705414960',
    projectId: 'ingredientbutler',
    storageBucket: 'ingredientbutler.appspot.com',
    iosClientId: '926705414960-136tr3n57i1s32mp8jvt0uiknc8hnra6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ingredientButler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM6wkHfZQDk0tnymlswHB1NjbZDzfwrto',
    appId: '1:926705414960:ios:7224ea9b2f5f0f3c19cef5',
    messagingSenderId: '926705414960',
    projectId: 'ingredientbutler',
    storageBucket: 'ingredientbutler.appspot.com',
    iosClientId: '926705414960-136tr3n57i1s32mp8jvt0uiknc8hnra6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ingredientButler',
  );
}
